### PR TITLE
feat: Default to latest version of infracost CLI

### PR DESCRIPTION
**Pull request by tim775**

### CODE REVIEW

**Comment by tim775** [comment]
Don't want to deal with rate limits

**Comment by aliscott** [comment]
> Don't want to deal with rate limits

Can we use the user's `GITHUB_TOKEN`?

**Comment by tim775** [comment]
Let me try that, then you can decide which PR to merge :)

**Comment by aliscott** [comment]
I wouldn't worry. I think the new way is better. I saw it in https://github.com/hashicorp-contrib/setup-packer but it looks like it needs another input which isn't great.

**Pull request closed without merging**
